apiVersion: v1
kind: Service
metadata:
  labels:
    app_name: auth-service
  name: auth-service
  namespace: t3
spec:
  ports:
  - name: port-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app_environment_id: auth-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
